wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.3
    start_time: 1647164204
    t:
      1:
      - 3
      2:
      - 3
      4: 3.7.3
      5: 0.12.11
      8:
      - 1
      - 5
